### PR TITLE
Nf ui auth downloaders

### PR DESCRIPTION
**Pull request by jgors**
add unit-tests and bug fix to assure_dict_from_str

### CODE REVIEW

**Comment by yarikoptic** [comment]
very nice -- thanks.  will merge whenever tests pass.
But once again -- next time try to minimize diff by not introducing changes elsewhere in the code base (suchas empty lines) -- causes conflicts upon merges etc.

**Comment by yarikoptic** [comment]
ok -- failures are due to a collection of your changes -- starting from that switch to requests implementation (e.g. error in get_tld) over to nearly a syntax error in test_assure_dict_from_str -- did you run those new tests locally before pushing?
Fixup at least that test for now -- work on downloaders should address the others eventually

**Comment by yarikoptic** [comment]
ok -- I will merge (need fixes) and fixup whatever was broken in the tests

**Comment by jgors** [comment]
yeah, had a meeting today, but in that code i fixed a bug you had (on line 65 of `providers.py`)

```
-        k, v = s.split('=', 1)
+        k, v = value_str.split('=', 1)
```

and the two unit-tests i added worked locally.  but that's why i pushed and did a pr against your branch -- to trigger travis and the docker imgs to see if it passed on those.

**Comment by yarikoptic** [comment]
no -- they didn't "work" locally for you since your tests had error in them so they could not "work".  see 13d921eb48f3688e3153ce738b0f86402baf1423

**Comment by jgors** [comment]
right, it worked when using `assert ==`, but changed it to the `assert_equal(...)` (right before pushing) to be compatible with your convention (and for nose) and missed changing a couple `==` to `,`.  was going to look into this after lunch.

**Pull request merged**
